fileversion: 3

robots:
  cf_0:
    enabled: false
    uri: radio://0/80/2M/E7E7E7E700
    initial_position: [0.0, 0.0, 0.0]
    type: cf21_mocap_deck

  cf_1:
    enabled: false
    uri: radio://0/80/2M/E7E7E7E701
    initial_position: [0.0, 0.0, 0.0]
    type: cf21_mocap_deck

  cf_2:
    enabled: true
    uri: radio://0/80/2M/E7E7E7E702
    initial_position: [0.0, 0.0, 0.0]
    type: cf21_mocap_deck

  cf_3:
    enabled: false
    uri: radio://0/80/2M/E7E7E7E703
    initial_position: [0.0, 0.0, 0.0]
    type: cf21_mocap_deck

  cf5:
    enabled: false
    uri: radio://0/80/2M/E7E7E7E705
    initial_position: [0.0, -0.5, 0.0]
    type: cf21

robot_types:
  cf21:
    motion_capture:
      tracking: "vendor"
      marker: default_single_marker
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8
      voltage_critical: 3.7

  cf21_mocap_deck:
    motion_capture:
      tracking: "vendor"
      marker: mocap_deck
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8
      voltage_critical: 3.7

all:
  firmware_params:
    commander:
      enHighLevel: 1
    stabilizer:
      estimator: 2
      controller: 1
    locSrv:
      extPosStdDev: 1e-3
      extQuatStdDev: 0.5e-1
  broadcasts:
    num_repeats: 15
    delay_between_repeats_ms: 1
